# docker-compose.yml
version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - ollama-network

  app:
    build: .
    container_name: python_app
    depends_on:
      - ollama
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    networks:
      - ollama-network
    restart: unless-stopped
    # Simplified command since model pulling is now handled in the LLM controller
    command: >
      sh -c "
        echo 'Waiting for Ollama to start...' &&
        sleep 10 &&
        python app.py
      "

networks:
  ollama-network:
    driver: bridge

volumes:
  ollama_data: